"""add business hours and scheduled processing

Revision ID: 9e86d59370a4
Revises: 8734b5ad51f7
Create Date: 2026-09-19 02:13:11.561687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e86d59370a4'
down_revision: Union[str, Sequence[str], None] = '8734b5ad51f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('is_open', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_of_week')
    )
    op.create_index(op.f('ix_business_hours_id'), 'business_hours', ['id'], unique=False)
    op.add_column('orders', sa.Column('scheduled_processing_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_orders_scheduled_processing_at'), 'orders', ['scheduled_processing_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_scheduled_processing_at'), table_name='orders')
    op.drop_column('orders', 'scheduled_processing_at')
    op.drop_index(op.f('ix_business_hours_id'), table_name='business_hours')
    op.drop_table('business_hours')
    # ### end Alembic commands ###
